server:
  port: 7000
---
spring:
  profiles:
    active: dev
  data:
    mongodb:
      database: product
      authentication-database: admin
      host: localhost
      port: 27017
      username: root
      password: root
  rabbitmq:
    password: guest
    username: guest
    port: 5672
    host: 127.0.0.1
---
spring:
  profiles:
    active: test
  data:
    mongodb:
      database: product
      authentication-database: admin
      host: localhost
      port: 27017
      username: root
      password: root
  rabbitmq:
    password: guest
    username: guest
    port: 5672
    host: 127.0.0.1
---
spring:
  profiles:
    active: prod
  data:
    mongodb:
      database: product
      authentication-database: admin
      host: localhost
      port: 27017
      username: root
      password: root
  rabbitmq:
    password: guest
    username: guest
    port: 5672
    host: 127.0.0.1